// Downloads the theme fonts from Google Fonts into public/fonts and writes the
// @font-face rules to src/fonts.css.
//
// They are self-hosted rather than linked, because the app has to work offline:
// a CDN link would leave the fonts missing with no connection, and the service
// worker already precaches woff2 from the build output.
//
// Run with: node scripts/fetch-fonts.mjs
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
// Inside src, not public: Vite then rewrites and hashes the URLs, so they stay
// correct under the GitHub Pages subpath. An absolute /fonts/ path would not.
const outDir = resolve(root, 'src/fonts')

// Only latin and latin-ext: Portuguese accents live in Latin-1, and the other
// subsets would triple the download for nothing.
const WANTED_SUBSETS = ['latin', 'latin-ext']

const FAMILIES = [
  { name: 'Quicksand', weights: [400, 700] },
  { name: 'Inter', weights: [400, 600] },
  { name: 'Sacramento', weights: [400] },
  { name: 'Amatic SC', weights: [400, 700] },
  { name: 'Caveat', weights: [400, 600] },
  { name: 'Indie Flower', weights: [400] },
  { name: 'Patrick Hand', weights: [400] },
]

// A desktop UA is what makes the API hand back woff2 rather than older formats.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

const slug = (s) => s.toLowerCase().replace(/\s+/g, '-')

mkdirSync(outDir, { recursive: true })

const faces = []

for (const family of FAMILIES) {
  const spec = `${family.name.replace(/ /g, '+')}:wght@${family.weights.join(';')}`
  const cssUrl = `https://fonts.googleapis.com/css2?family=${spec}&display=swap`
  const css = await (await fetch(cssUrl, { headers: { 'User-Agent': UA } })).text()

  // Each block is preceded by a comment naming its subset.
  const blocks = css.split('/*').slice(1)

  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf('*/')).trim()
    if (!WANTED_SUBSETS.includes(subset)) continue

    const weight = Number(block.match(/font-weight:\s*(\d+)/)?.[1])
    const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1]
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim()
    if (!weight || !url) continue

    const file = `${slug(family.name)}-${weight}-${subset}.woff2`
    const bytes = Buffer.from(await (await fetch(url)).arrayBuffer())
    writeFileSync(resolve(outDir, file), bytes)
    console.log(`${file}  ${(bytes.length / 1024).toFixed(1)} kB`)

    faces.push(
      [
        '@font-face {',
        `  font-family: '${family.name}';`,
        '  font-style: normal;',
        `  font-weight: ${weight};`,
        '  font-display: swap;',
        `  src: url('./fonts/${file}') format('woff2');`,
        range ? `  unicode-range: ${range};` : null,
        '}',
      ]
        .filter(Boolean)
        .join('\n'),
    )
  }
}

const header = `/* Generated by scripts/fetch-fonts.mjs -- do not edit by hand.
 *
 * Self-hosted so the app keeps its fonts offline. Licences are in
 * FONT-LICENCES.md at the repo root.
 */\n\n`

writeFileSync(resolve(root, 'src/fonts.css'), header + faces.join('\n\n') + '\n')
console.log(`\n${faces.length} faces -> src/fonts.css`)
